name: Build

on:
  push:
    branches: ['main']
    tags: ['v*']
  pull_request:
    branches: ['main']
  workflow_dispatch:

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - platform:  'linux/amd64'
            name: moekoemusic-lite
            os: 'ubuntu-latest'
          - platform:  'windows/amd64'
            name: moekoemusic-lite.exe
            os: 'windows-latest'
          - platform:  'darwin/universal'
            name: moekoemusic-lite
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup PNPM
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: 22

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Install Go Modules
        run: go mod download

      - name: Build
        run: pnpm build -devtools -o ${{ matrix.build.name }} -platform ${{ matrix.build.platform }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.build.name }}-${{ matrix.build.platform }}
          path: 'build/bin/*'

      - name: Release
        uses: ncipollo/release-action@v1
        if: ${{ github.ref_type == 'tag' }}
        with:
          artifacts: 'build/bin/*'
          draft: true
          name: 'Moekoe Music Lite ${{ github.ref_name }}'
