name: Wails build

on:
  push:
    branches: ['main']
    tags: ['v*']
  workflow_dispatch:

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - platform:  'windows/amd64'
            os: 'windows-latest'
          - platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup PNPM
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: 22

      - name: Build wails
        uses: dAppCore/build@v4.0.0
        id: build
        with:
          build-name: moekoemusic-lite
          build-platform: ${{ matrix.build.platform }}
